### ISSUE TITLE
Bəzi xırda səhvlər

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Amin0122/PragmatechFoundationProject#14]
**[Burada](https://github.com/Amin0122/PragmatechFoundationProject/blob/main/ProjectFrontEnd/Footer/css/footer.css#L63)** 1 vergül qoyulmalıdır.

**Comment by isbendiyarovanezrin** [comment]
**[Burada](url)** şəkil "img" adlı (adı başqa da ola bilər) qovluqda olmalıdır.

**Comment by isbendiyarovanezrin** [comment]
Kodlar arasında çox boşluq, ara qoymayın. Səliqəsiz görünür və oxunaqlılığını azaldır.

**Comment by Amin0122** [comment]
oldu cox sagolun duzelderem
