### ISSUE TITLE
JavaScriptlə bağlı işlərinizi "ProjectBackEnd" qovluğuna əlavə etməyin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Amin0122/PragmatechFoundationProject#25]
Ayrıca "JavaScript" adlı qovluq açıb ona əlavə edə bilərsiniz (qovluğu "Works" qovluğunun içində də yarada bilərsiniz).

**Comment by Amin0122** [comment]
salam deyisdirdim
