### ISSUE TITLE
<header> teqindən istifadə edin

### ISSUE THREAD

**Issue by isbendiyarovanezrin** [Amin0122/PragmatechFoundationProject#4]
[Bu](https://github.com/Amin0122/PragmatechFoundationProject/blob/main/Works/WEB%20%20PAGE/index.html#L12) hissədə `<section id="header"> . . . </section>`  teqindən istifadə etməkdənsə birbaşa `<header></header>` teqindən istifadə edə bilərsiniz. Teq haqqında daha ətraflı [bu](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) qaynaqdan oxuya bilərsiniz.

**Comment by Amin0122** [comment]
oldu cox  sagolun
